services:
  redis:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: redis
    ports:
      - "6379:6379"
    restart: unless-stopped
    volumes:
      - redis_data:/data

volumes:
  redis_data:

