[tool.poetry]
name = "chromium-rce-exploit"
version = "1.0.0"
description = "Chromium V8 Engine RCE Exploit Demo (CVE-2025-1002)"
authors = ["Browser Security Team <susan@fireeye.com>"]
readme = "README.md"
packages = [{include = "browser_exploit"}]

[tool.poetry.dependencies]
python = "^3.8"
colorama = "^0.4.6"
pyfiglet = "^0.8.0"
requests = "^2.31.0"

[tool.poetry.scripts]
browser-exploit = "browser_exploit.main:main"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
