[project]
name = "cve-2025-5054"
version = "0.1.0"
description = "A Python tool to detect if your Ubuntu system is vulnerable to CVE-2025-5054 (Apport race condition)."
readme = "README.md"
license = "MIT"
requires-python = ">=3.12"
dependencies = []
