server:
  port: 8080

spring:
  application:
    name: vulnerable-gateway
  cloud:
    gateway:
      actuator:
        verbose:
          enabled: true

management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    gateway:
      enabled: true

logging:
  level:
    org.springframework.cloud.gateway: DEBUG