[project]
name = "CVE-2023-40289"
description = "Exploit for CVE-2023-40289, a command injection vulnerability in several Baseband Management Controllers (BMC) by with firmware by ATEN"
version = "0.1"
requires-python = ">=3.10"
dependencies = [
    "click>=8.0",
    "requests>=2.0",
]
readme = "README.md"
license = "MIT"

[project.scripts]
CVE-2023-40289 = "CVE_2023_40289:cli"
