name: CVE Check

on:
  schedule:
    # Run every 1 hour
    - cron: '0 * * * *'
  push:
    branches:
      - main

# Actions project permission
permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Check out repository
      uses: actions/checkout@v3

    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: '1.23.0'  # Specify the version of Go you want to use

    - name: Run CVE mapping command
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: |
        echo '"CVE-2025-"' | go run cvemapping.go -github-token "$GITHUB_TOKEN" -page 1 -year 2025
        echo '"CVE-2024-"' | go run cvemapping.go -github-token "$GITHUB_TOKEN" -page 1 -year 2024
        echo '"CVE-2023-"' | go run cvemapping.go -github-token "$GITHUB_TOKEN" -page 1 -year 2023
        echo '"CVE-2022-"' | go run cvemapping.go -github-token "$GITHUB_TOKEN" -page 1 -year 2022
        echo '"CVE-2021-"' | go run cvemapping.go -github-token "$GITHUB_TOKEN" -page 1 -year 2021
        echo '"CVE-2020-"' | go run cvemapping.go -github-token "$GITHUB_TOKEN" -page 1 -year 2020

    - name: Commit and push changes if there are any
      run: |
        git config --global user.name 'GitHub Actions'
        git config --global user.email 'actions@users.noreply.github.com'
        git add .
        
        # Check if there are changes before committing
        if ! git diff --cached --exit-code; then
          IST_DATE=$(TZ='Asia/Kolkata' date +'%a %b %d %H:%M:%S IST %Y')
          git commit -m "Updated List: $IST_DATE"
          git push
        else
          echo "No changes to commit"
        fi
